# Generated by Django 4.0.3 on 2022-04-02 19:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=250)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('budget', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['departure_date'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('date', models.DateField()),
                ('transportation', models.CharField(max_length=250)),
                ('accomodation', models.CharField(max_length=250)),
                ('things_to_do', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None)),
                ('meals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('daily_budget', models.IntegerField(default=0)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='main_app.travel')),
            ],
        ),
    ]
