# Generated by Django 4.0.3 on 2022-04-01 21:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('date', models.DateField()),
                ('transportation', models.CharField(max_length=250)),
                ('accomodation', models.CharField(max_length=250)),
                ('things_todo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None)),
                ('meals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='main_app.travel')),
            ],
        ),
    ]
