# Generated by Django 4.0.3 on 2022-04-02 19:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('things_to_do', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, size=None)),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='main_app.destination'),
        ),
        migrations.AddField(
            model_name='travel',
            name='destinations',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.destination'),
        ),
    ]
