# Generated by Django 4.0.3 on 2022-04-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tag_destination_continent_list_travel_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='destination',
            name='continent',
            field=models.CharField(choices=[('Oceania', 'Oceania'), ('Europe', 'Europe'), ('Antarctica', 'Antarctica'), ('North America', 'North America'), ('Sourth America', 'South America'), ('Asia', 'Asia'), ('Africa', 'Africa')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='category',
            field=models.CharField(choices=[('Packing List', 'Packing List'), ('To Do List', 'To Do List'), ('Check List', 'Check List')], max_length=20),
        ),
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=models.CharField(choices=[('Medium', 'Medium'), ('None', 'None'), ('High', 'High'), ('Low', 'Low')], max_length=20),
        ),
    ]
