# Generated by Django 4.0.3 on 2022-04-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_tag_tag_name_alter_destination_continent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='continent',
            field=models.CharField(choices=[('Sourth America', 'South America'), ('Antarctica', 'Antarctica'), ('Europe', 'Europe'), ('Asia', 'Asia'), ('Oceania', 'Oceania'), ('Africa', 'Africa'), ('North America', 'North America')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='category',
            field=models.CharField(choices=[('To Do List', 'To Do List'), ('Packing List', 'Packing List'), ('Check List', 'Check List')], max_length=20),
        ),
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=models.CharField(blank=True, choices=[('Medium', 'Medium'), ('High', 'High'), ('None', 'None'), ('Low', 'Low')], max_length=20),
        ),
    ]
