# Generated by Django 4.0.3 on 2022-04-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='img',
        ),
        migrations.AddField(
            model_name='travel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='travel',
            name='img_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.travel'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='destinations',
            field=models.ManyToManyField(blank=True, to='main_app.destination'),
        ),
    ]
