# Generated by Django 4.0.3 on 2022-04-12 09:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_destination_continent_alter_list_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['category', 'is_completed']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='travel_bucket_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='travel',
            name='things_to_do',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='destination',
            name='continent',
            field=models.CharField(choices=[('Oceania', 'Oceania'), ('Antarctica', 'Antarctica'), ('North America', 'North America'), ('Africa', 'Africa'), ('Europe', 'Europe'), ('Asia', 'Asia'), ('Sourth America', 'South America')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='category',
            field=models.CharField(choices=[('To Do List', 'To Do List'), ('To Confrim List', 'To Do List'), ('Packing List', 'Packing List')], max_length=20),
        ),
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('None', 'None'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20),
        ),
    ]
