# Generated by Django 4.0.3 on 2022-04-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_travel_img_travel_image_travel_img_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='img',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='img_url',
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destination_images/'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travel_images/'),
        ),
    ]
