# Generated by Django 4.0.4 on 2022-04-12 20:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_list_options_customuser_travel_bucket_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='continent',
            field=models.CharField(choices=[('Sourth America', 'South America'), ('Europe', 'Europe'), ('Oceania', 'Oceania'), ('Africa', 'Africa'), ('North America', 'North America'), ('Asia', 'Asia'), ('Antarctica', 'Antarctica')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='list',
            name='category',
            field=models.CharField(choices=[('To Do List', 'To Do List'), ('Packing List', 'Packing List'), ('To Confrim List', 'To Do List')], max_length=20),
        ),
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('None', 'None'), ('Low', 'Low')], max_length=20),
        ),
        migrations.AlterField(
            model_name='travel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
