# Generated by Django 4.0.4 on 2022-04-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_destination_continent_alter_list_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='continent',
            field=models.CharField(choices=[('Asia', 'Asia'), ('Oceania', 'Oceania'), ('Europe', 'Europe'), ('Sourth America', 'South America'), ('North America', 'North America'), ('Africa', 'Africa'), ('Antarctica', 'Antarctica')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destination_images/'),
        ),
        migrations.AlterField(
            model_name='list',
            name='category',
            field=models.CharField(choices=[('To Confrim List', 'To Do List'), ('To Do List', 'To Do List'), ('Packing List', 'Packing List')], max_length=20),
        ),
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('None', 'None'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20),
        ),
        migrations.AlterField(
            model_name='travel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travel_images/'),
        ),
    ]
