# Generated by Django 4.0.4 on 2022-04-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_destination_continent_alter_list_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='continent',
            field=models.CharField(choices=[('Oceania', 'Oceania'), ('Africa', 'Africa'), ('Europe', 'Europe'), ('North America', 'North America'), ('Asia', 'Asia'), ('Sourth America', 'South America'), ('Antarctica', 'Antarctica')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='category',
            field=models.CharField(choices=[('To Do List', 'To Do List'), ('To Confirm List', 'To Confirm List'), ('Packing List', 'Packing List')], max_length=20),
        ),
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Low', 'Low'), ('None', 'None'), ('Medium', 'Medium')], max_length=20),
        ),
    ]
